services:
  personal-task-manager:
    container_name: personal-task-manager
    image: app-task-manager-nextjs:v1
    ports:
      - "7189:3000"
    restart: always
    volumes:
      - ./dev.db:/app/dev.db  # Monte le fichier SQLite sur le conteneur
      - ./prisma:/app/prisma   # Garde Prisma accessible depuis le conteneur
